### ISSUE TITLE
Is there an option to hide recipient-key-id

### ISSUE THREAD

**Issue by martgil** [vanitasvitae/pgpainless#375]
Greetings,

Does pgpainless offers a feature similar to `gpg`'s [--hide-recipient](https://www.gnupg.org/documentation/manuals/gnupg/GPG-Key-related-Options.html) or OpenPGP.js [wildcard](https://docs.openpgpjs.org/global.html#encrypt) option?

Best regards,
Mart

**Comment by vanitasvitae** [comment]
Hi Mart,

Unfortunately, BouncyCastle (which PGPainless internally uses) does not currently support producing messages with wildcard recipients.
So in order to add support for this in PGPainless, we'd need to add support for it to BouncyCastle first.

Support in BouncyCastle would probably involve adding a property to the PublicKeyKeyEncryptionMethodGenerator class, such that if wildcards are enabled, [this line](https://github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/openpgp/operator/PublicKeyKeyEncryptionMethodGenerator.java#L123) would pass `0` instead of `pubKey.getKeyID()` to the `PublicKeyEncSessionPacket` constructor.

**Comment by vanitasvitae** [comment]
I created a patch for BC adding support for producing messages using wildcard-ids.

https://github.com/bcgit/bc-java/pull/1384

Edit: Feel free to voice your support for such a patch in the upstream PR ;)
Edit2: To be clear, PGPainless already supports decrypting messages that are addressed to a wild-card key-id simply by trial and error.

**Comment by martgil** [comment]
Understood - Thank you very much!

**Comment by vanitasvitae** [comment]
The Bouncycastle team merged the proposed patch, so PGPainless will add support for wildcard key-ids once BC 1.74 is out :)

**Comment by martgil** [comment]
thank you very much for the help 🙏 :)

**Comment by vanitasvitae** [comment]
BC 1.74 has apparently [been released yesterday](https://www.bouncycastle.org/releasenotes.html#r1rv74), but it is not yet up on maven central. Once it is available, I can merge #381 and close this issue :)

**Comment by DenBond7** [comment]
Hi @vanitasvitae,
Do you have soon plans to update PGPainless with these changes?

**Comment by vanitasvitae** [comment]
Yep, I'm right in the process of creating a release :)

**Comment by vanitasvitae** [comment]
1.5.4 has been released :)
