### ISSUE TITLE
pgpainless-cli generate-key should reject non-UTF-8 bytestrings as user IDs

### ISSUE THREAD

**Issue by dkg** [vanitasvitae/pgpainless#395]
As noted over in https://gitlab.com/sequoia-pgp/openpgp-interoperability-test-suite/-/issues/113#note_1460952463, the following command succeeds where it should probably fail:

```
pgpainless-cli generate-key "$(printf '\xfd')"
```

Rather than encoding the non-UTF-8 string as a non-compliant user ID, it appears that it creates a user ID with the single UTF-8 character `U+FFFD REPLACEMENT CHARACTER`, encoded in the User ID packet as the three-octet sequence `ef bf bd`.

**Comment by vanitasvitae** [comment]
Thanks for keeping track of this issue :)

**Comment by vanitasvitae** [comment]
I'm just looking into this.
In Java, the entry-point to a program is the `main(String[] args)` method, which takes as argument an array of Strings. Since Strings by nature are UTF8 encoded, the main method cannot be called with non-UTF8 data. If non-UTF8 data is passed to a Java application, I suppose it is UTF-8 decoded *before* being passed to the main method, resulting into the U+FFFD replacement characters observed above.

I guess there is not much we can do on the Java side :/
Note, that user-ids are of course a special case here, since non-UTF8 data CAN make it into Java-SOP implementation via an indirect data type.

**Comment by vanitasvitae** [comment]
@dkg btw. I just implemented SOP-07: https://github.com/pgpainless/sop-java/pull/20, https://github.com/pgpainless/pgpainless/pull/397 ;)

**Comment by dkg** [comment]
This is pretty disappointing, but i see how the system seems to constrain you here ☹

Have you considered/tested [-Xargencoding](https://eclipse.dev/openj9/docs/xargencoding/) or similar ways to fiddle with how java interprets its arguments?  i recognize that might be overkill/cause breakage for other arguments too, i'm just trying to understand what the options are.

**Comment by vanitasvitae** [comment]
I haven't tested that yet, but I'm also not sure, if its really worth it tbh.
Since PGPainless first and foremost is a Java API and its SOP implementation does not even allow a user to input a non-UTF8 userID (the API only offers a method taking a String as argument), enforcing this on the CLI layer really only prevents an edge case imho. Since non-UTF8 output does not even result in broken user-IDs (instead, broken UTF8 is replaced with a safe encoding), I don't think it is worth the hassle to also detect non-UTF8 and throw an exception.

I might consider it though, if it isn't too much effort :D

**Comment by dkg** [comment]
Alternately: what if `pgpainless-cli` were to reject any User ID that contains `U+FFFD REPLACEMENT CHARACTER` ?

I'd appreciate your thoughts over on https://gitlab.com/dkg/openpgp-stateless-cli/-/issues/81, whether that's useful (i'm also happy to hear "this sounds like a bad idea, don't do it")
