### ISSUE TITLE
Consider some checkstyle-like linting for Kotlin

### ISSUE THREAD

**Issue by vanitasvitae** [vanitasvitae/pgpainless#408]
Currently, the Kotlin code added in the pgpainless2 branch is not linted, since checkstyle only works for Java.

We should consider using something like Detekt (https://medium.com/@danielvivek/code-styling-for-kotlin-fa7a8291c254) to lint the Kotlin code.

**Comment by msfjarvis** [comment]
For code formatting purposes I'm personally biased towards [ktfmt](https://github.com/facebook/ktfmt) since it doesn't have many knobs to fiddle around with and it tries to match broadly how [google-java-format](https://github.com/google/google-java-format) works. I can send in a PR if you're willing to try it out.

**Comment by vanitasvitae** [comment]
That would be awesome!

**Comment by msfjarvis** [comment]
@vanitasvitae GitHub didn't auto-close this issue since it was merged into a non-default branch, you'll have to do it manually.
